from django.conf.urls import url

from django_chinese_medicine import views

urlpatterns = [
    url(r'^etiologie/neu/$', views.EtiologieAdd.as_view(), 
        name='etiologie_add'),
    url(r'^etiologie/(?P<slug>[-\w]+)/$', views.EtiologieDetail.as_view(), 
        name='etiologie_detail'),
    url(r'^etiologie/(?P<slug>[-\w]+)/bearbeiten$', views.EtiologieEdit.as_view(), 
        name='etiologie_edit'),
    url(r'^etiologien/(?P<slug>[-\w]+)/schreddern/$', views.EtiologieRemove.as_view(), 
        name='etiologie_remove'),
    url(r'^etiologien/$', views.EtiologieIndex.as_view(), 
        name='etiologie_index'),
    url(r'^krankheitsmuster/neu/$', views.DiseaseAdd.as_view(), 
        name='disease_add'),
    url(r'^krankheitsmuster/$', views.DiseaseIndex.as_view(), 
        name='disease_index'),
    url(r'^krankheitsmuster/(?P<slug>[-\w]+)/schreddern/$', views.DiseaseRemove.as_view(),
        name='disease_remove'),
    url(r'^krankheitsmuster/(?P<slug>[-\w]+)/bearbeiten/$', views.DiseaseEdit.as_view(),
        name='disease_edit'),
    url(r'^krankheitsmuster/(?P<slug>[-\w]+)/$', views.DiseaseDetail.as_view(),
        name='disease_detail'),
    url(r'^therapie/add/$', views.TherapyCreate.as_view(), 
        name='therapy_add'),
    url(r'^therapie/(?P<slug>[-\w]+)/$', views.TherapyDetail.as_view(),
        name='therapy_detail'),
    url(r'^therapie/(?P<slug>[-\w]+)/bearbeiten/$', views.TherapyEdit.as_view(),
        name='therapy_edit'),
    url(r'^therapie/(?P<slug>[-\w]+)/schreddern/$', views.TherapyRemove.as_view(),
        name='therapy_remove'),
    url(r'^therapien/$', views.TherapyIndex.as_view(), 
        name='therapy_index'),
    url(r'^symptom/neu/$', views.SymptomAdd.as_view(), 
        name='symptom_add'),
    url(r'^symptom/(?P<slug>[-\w]+)/bearbeiten/$', views.SymptomEdit.as_view(),
        name='symptom_edit'),
    url(r'^symptom/(?P<slug>[-\w]+)/schreddern/$', views.SymptomRemove.as_view(),
        name='symptom_remove'),
    url(r'^symptom/(?P<slug>[-\w]+)/$', views.SymptomDetail.as_view(),
        name='symptom_detail'),
    url(r'^symptome/$', views.SymptomIndex.as_view(), 
        name='symptom_index'),
    url(r'^$', views.Main.as_view(), 
        name='main'),
]
