# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeseasePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('manifestation', models.TextField(blank=True, max_length=1024)),
                ('tongue', models.TextField(blank=True, max_length=1024)),
                ('puls', models.CharField(max_length=255)),
                ('pathologie', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'TherapieMuster',
            },
        ),
        migrations.CreateModel(
            name='Etiologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name': '\xc4tiologie',
                'verbose_name_plural': '\xc4tiologien',
            },
        ),
        migrations.CreateModel(
            name='Therapie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name': 'Therapie',
                'verbose_name_plural': 'Therapien',
            },
        ),
        migrations.AddField(
            model_name='deseasepattern',
            name='etiologie',
            field=models.ManyToManyField(to='disease.Etiologie'),
        ),
    ]
