# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('manifestation', models.TextField(blank=True, max_length=1024)),
                ('tongue', models.TextField(blank=True, max_length=1024)),
                ('puls', models.CharField(max_length=255)),
                ('pathologie', models.CharField(max_length=255)),
                ('etiologie', models.ManyToManyField(blank=True, to='disease.Etiologie')),
            ],
            options={
                'verbose_name': 'TherapieMuster',
                'verbose_name_plural': 'TherapieMuster',
            },
        ),
        migrations.RemoveField(
            model_name='deseasepattern',
            name='etiologie',
        ),
        migrations.DeleteModel(
            name='DeseasePattern',
        ),
        migrations.AddField(
            model_name='therapie',
            name='disease',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='disease.DiseasePattern'),
            preserve_default=False,
        ),
    ]
