# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20160309_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name': 'Befund',
                'verbose_name_plural': 'Befunde',
            },
        ),
        migrations.AddField(
            model_name='diseasepattern',
            name='results',
            field=models.ManyToManyField(blank=True, to='disease.Result'),
        ),
    ]
