# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20160309_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='name',
            new_name='resut',
        ),
        migrations.AddField(
            model_name='result',
            name='spot',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
