# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_auto_20160309_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='resut',
            new_name='result',
        ),
    ]
