# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20160309_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasepattern',
            options={'verbose_name': 'KrankheitsMuster', 'verbose_name_plural': 'KrankheitsMuster'},
        ),
        migrations.AlterField(
            model_name='therapie',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.DiseasePattern'),
        ),
    ]
