# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0007_auto_20160310_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='disease',
        ),
        migrations.AddField(
            model_name='diseasepattern',
            name='therapy',
            field=models.ManyToManyField(blank=True, to='disease.Therapy'),
        ),
    ]
