# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0008_auto_20160310_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasepattern',
            name='puls',
        ),
        migrations.RemoveField(
            model_name='diseasepattern',
            name='tongue',
        ),
        migrations.AddField(
            model_name='therapy',
            name='action',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
