# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0009_auto_20160310_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapy',
            old_name='action',
            new_name='intension',
        ),
    ]
